lessons/lesson14/faq/faq/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('faq_app.urls')),
    path('users/', include('django.contrib.auth.urls'))
]

lessons/lesson14/faq/faq_app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = "faq"
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('register', views.RegisterView.as_view(), name='register'),
	path('question/new', views.CreateQuestion.as_view(), name='new_question'),
	path('question/<int:pk>', views.UpdateQuestion.as_view(), name='update_quesdtion'),
	path('question/delete/<int:pk>', views.DeleteQuestion.as_view(), name='delete_question'),
]

lessons/lesson14/faq/faq_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.

class UserQuestion(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	body = models.CharField(max_length=255)
	pub_date = models.DateTimeField(default=timezone.now())

class Answer(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	question = models.ForeignKey(UserQuestion, on_delete=models.CASCADE)
	body = models.CharField(max_length=255)
	pub_date = models.DateTimeField(default=timezone.now())
	likes = models.IntegerField(default=0)
	dislikes = models.IntegerField(default=0)
	best_answer = models.BooleanField(default=False)

class UserLikes(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
	like_date = models.DateTimeField(default=timezone.now())

class UserDislikes(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
	dislike_date = models.DateTimeField(default=timezone.now())

lessons/lesson14/faq/faq_app/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm

from .models import *

#from .models import *
# Create your views here.
class IndexView(generic.ListView):
	model = UserQuestion
	# сам создает template_name: userquestion_list?
	template_name = "faq/index.html"

	def get_query_set(self):
		return UserQuestion.objects.all().order_by('pub_date')

class DetailView(generic.DetailView):
	model = UserQuestion
	template_name = "faq/detail.html"

class RegisterView(generic.edit.FormView):
	form_class = UserCreationForm
	success_url = "users/login"
	template_name = "registration/register.html"

	def form_valid(self, form):
		form.save()
		return super().form_valid(form)

	def form_invalid(self, form):
		return super().form_invalid(form)


class CreateQuestion(generic.edit.CreateView):
	model = UserQuestion
	template_name = "faq/create_question.html"
	fields = ['title', 'body']
	# success_url = "/"

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)		

	def get_success_url(self):
		return reverse("faq:index")

class UpdateQuestion(generic.edit.UpdateView):
	model = UserQuestion
	template_name = "faq/update_question.html"
	fields = ['title', 'body']

	def get_success_url(self):
		return reverse("faq:index")

class DeleteQuestion(generic.edit.DeleteView):
	model = UserQuestion
	template_name = "faq/question_confirm_delete.html"

	def get_success_url(self):
		return reverse("faq:index")
		

lessons/lesson14/faq/faq_app/templates/faq/create_question.html
<form action="" method="post">
	{% csrf_token %}

	{{ form.as_p }}
	<input type="submit" value="Save">
</form>

lessons/lesson14/faq/faq_app/templates/faq/detail.html
<div>
	<h3><b>{{ object.user.username }}</b></h3>
	<h1>{{ object.title }}</h1>
	<p>{{ object.body }}</p>
	<p><i>{{ object.pub_date }}</i></p>
</div>

<div>
	{% for a in object.answer_set.all %}
	<div>
		<h3>{{ a.user.username }}</h3>
		<p>{{ a.body }}</p>
		<p>{{ a.likes }} likes</p>
		<p>{{ a.dislikes }} dislikes</p>
		<p><b>{{ a.best_answer}}</b></p>
		<p><i>{{ a.pub_date }}</i></p>
	</div>
	{% endfor %}
</div>

lessons/lesson14/faq/faq_app/templates/faq/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<ol>
		{% for q in object_list %}
			<li><a href="{% url 'faq:detail' q.id %}">{{ q.title }}</a></li>	
		{% endfor %}
	</ol>
</body>
</html> 

lessons/lesson14/faq/faq_app/templates/faq/question_confirm_delete.html
<form action="" method="post">
	{% csrf_token %}
	
	<p>Are you sure you want to delete {{ object.title }}?</p>
	<input type="submit" value="Confirm">
</form>

lessons/lesson14/faq/faq_app/templates/faq/update_question.html
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Update">
</form>