homeworks/homework14/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls'))
]

homeworks/homework14/blog/blog_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "blog_app"
urlpatterns = [	
	path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:post_id>/create_comment/', views.create_comment, name='create_comment'),
	path('login/', auth_views.LoginView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('register/', views.RegisterView.as_view(), name='register'),
	path('new/', views.CreatePostView.as_view(), name='new_post'),
	path('<int:pk>/edit', views.UpdatePostView.as_view(), name='edit_post'),
	path('<int:pk>/delete', views.DeletePostView.as_view(), name='delete_post'),

]

homeworks/homework14/blog/blog_app/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
	title = models.CharField(max_length=144)
	body = models.CharField(max_length=1024)
	pub_date = models.DateTimeField(default=timezone.now());
	user = models.CharField(max_length=32)

	def __str__(self):
		return self.title

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	body = models.CharField(max_length=144)
	pub_date = models.DateTimeField(default=timezone.now())
	user = models.CharField(max_length=32)

	def __str__(self):
		return self.body

homeworks/homework14/blog/blog_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

class CommentForm(forms.Form):
	post = forms.IntegerField(required=True, widget=forms.HiddenInput())
	user = forms.CharField(label="User", max_length=32)	
	body = forms.CharField(widget=forms.Textarea)


	

homeworks/homework14/blog/blog_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
# from django.contrib.auth import authenticate, login

from .models import Post, Comment
from .forms import RegistrationForm, CommentForm

# Create your views here.
# def index(request):
# 	posts = Post.objects.order_by("pub_date")
# 	return render(request, "blog_app/index.html", {"posts": posts})

# def detail(request, post_id):
# 	post = get_object_or_404(Post, pk=post_id)
# 	return render(request, "blog_app/detail.html", {"post": post})


class IndexView(generic.ListView):
	template_name = "blog_app/index.html"
	context_object_name = "posts"

	def get_queryset(self):
		return Post.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")

class DetailView(generic.DetailView):
	model = Post
	# автоматом поставит "post_detail.html"
	# template_name = "blog_app/detail.html"

	def get_queryset(self):
		return Post.objects.filter(pub_date__lte=timezone.now())

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["form"] = CommentForm()
		return context


class RegisterView(generic.edit.FormView):
	form_class = RegistrationForm
	success_url = "/login"
	template_name = "registration/register.html"

	def form_valid(self, form):
		# user = authenticate(self.request, username=self.request.POST['username'], password=self.request.POST['password1'])
		# login(self.request, self.request.user)
		
		form.save()
		return super(RegisterView, self).form_valid(form)

	def form_invalid(self, form):
		return super(RegisterView, self).form_invalid(form)


class CreatePostView(generic.edit.CreateView):
	model = Post
	template_name = "blog_app/new_post.html"
	fields = ['title', 'body']

	def form_valid(self, form):
	
		form.instance.user = self.request.user
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("blog_app:index")


class UpdatePostView(generic.edit.UpdateView):
	model = Post
	template_name = "blog_app/update_post.html"
	fields = ['title', 'body']


	def get_success_url(self):
		return reverse("blog_app:index")

class DeletePostView(generic.edit.DeleteView):
	model = Post
	template_name = "blog_app/delete_post.html"

	def get_success_url(self):
		return reverse("blog_app:index")
		



def create_comment(request, post_id):	
	if(request.method == "POST"):
		form = CommentForm(request.POST)
		if(form.is_valid()):
			#post = get_object_or_404(Post, pk=post_id)
			form.post = post_id 
			return HttpResponseRedirect(reverse('blog_app:index'))
		else: 
			form = CommentForm()

		return render(request, "blog_app/detail.html", {"form": form})

homeworks/homework14/blog/blog_app/templates/blog_app/delete_post.html
{% extends "blog_app/navbar.html" %}


{% block content %}
	<form action="" method="post">
		{% csrf_token %}
	

		<h5>Delete post "<span class="teal-text lighten-1">{{ object }}</span>" ?</h5>
		<input type="submit" value="Delete" class="btn-small">
	</form>
{% endblock %}

homeworks/homework14/blog/blog_app/templates/blog_app/detail.html
{% extends "blog_app/navbar.html" %}

{% block content %}
	<div class="container">
		<h1>{{ post }}</h1>
		<p>{{ post.body }}</p>
		<br><br><br>

		<div id="comments">
			<ol>
				{% for comment in post.comment_set.all %}
					<li><a href="">{{ comment }}</a></li>
				{% endfor %}
			</ol>
		</div>

		<br><br><br>
		<div class="row">
			<form class="col s6">
				{% csrf_token %}
				{{ form.as_p}}

				<!-- <div class="input_field">
					<textarea id="comment" class="materialize-textarea">
					</textarea>
					<label for="comment">Leave a comment...</label>
				</div>
				<div class="input_field">
					<input type="text" name="user">
					<label for="user">Your username: </label>
				</div>
				<br><br> -->
				<input type="submit" name="" class="btn-small" value="Comment" >
			</form>
		</div>
	</div>
{% endblock %}

homeworks/homework14/blog/blog_app/templates/blog_app/index.html
{% extends "blog_app/navbar.html" %}

{% block content %}
	<div class="container">
		<div class="row">
		<div class="col s8 offset-s2">

			{% if posts %} 
				{% for post in posts %}
						<a href="{% url 'blog_app:detail' post.id %}" class="black-text">
							<div class="card">
								<div class="card-content">
									<span class="card-title">{{ post }}</span>
									<p>{{ post.body }}</p>
									<div class="card-action">
										<span>
											{{ post.comment_set.count }} comments 
										</span>
									</div>
								</div>
							</div>
						</a>
						<br>
					{% endfor %}

					<!-- <ul>
						{% for post in posts %}
						<li><a href="{% url 'blog_app:detail' post.id %}">{{ post }}</a></li>
						{% endfor %}
					</ul> -->
				{% else %}
					<p>No posts yet</p>
				{% endif %}
		</div>
		</div>
	</div>
{% endblock %}

homeworks/homework14/blog/blog_app/templates/blog_app/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Blog</title>

	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 	'materialize.min.css' %}">

</head>
<body>
	<div class="navbar-fixed">
		<nav>
		  <div class="nav-wrapper black">
		    <a href="{% url 'blog_app:index' %}" class="brand-logo">Blog</a>
		    
		  {% if user.is_authenticated %}
	    	<ul class="right hide-on-med-and-down">
	    	  <li><a href="{% url 'blog_app:new_post' %}" class="btn-small">Create post</a></li>	
		      <li>{{ user.username }}</li>
		      <li><a href="{% url 'blog_app:logout' %}">Log out</a></li>
		    </ul>	
	    {% else %}
	    	<ul class="right hide-on-med-and-down">
		      <li><a href="{% url 'blog_app:login' %}">Sign in</a></li>
		      <li><a href="{% url 'blog_app:register' %}">Sign up</a></li>
		    </ul>
		 	{% endif %}	
		  </div>
		</nav>
	</div>

	<div class="container">
	{% block content %}
	{% endblock %}
	</div>
</body>
</html>

homeworks/homework14/blog/blog_app/templates/blog_app/new_post.html
{% extends "blog_app/navbar.html" %}


{% block content %}
	<h5>New post</h5>

	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Create" class="btn-small">
	</form>
{% endblock %}

homeworks/homework14/blog/blog_app/templates/blog_app/post_detail.html
{% extends "blog_app/navbar.html" %}

{% block content %}
	<div class="container">
		<h1>{{ post }}</h1>
		<p>{{ post.body }}</p>
		<br><br><br>

		<div id="comments">
			<ol>
				{% for comment in post.comment_set.all %}
					<li><a href="">{{ comment }}</a></li>
				{% endfor %}
			</ol>
		</div>

		<br><br><br>
		<div class="row">
			<form class="col s6">
				{% csrf_token %}
				{{ form.as_p}}

				<!-- <div class="input_field">
					<textarea id="comment" class="materialize-textarea">
					</textarea>
					<label for="comment">Leave a comment...</label>
				</div>
				<div class="input_field">
					<input type="text" name="user">
					<label for="user">Your username: </label>
				</div>
				<br><br> -->
				<input type="submit" name="" class="btn-small" value="Comment" >
			</form>
		</div>
	</div>
{% endblock %}

homeworks/homework14/blog/blog_app/templates/blog_app/update_post.html
{% extends "blog_app/navbar.html" %}

{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Uddate" class="btn-small">
	</form>
{% endblock %}