controls/control2/flankyshop/flankyshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fs.urls')),
    path('users/', include('django.contrib.auth.urls'))
]

controls/control2/flankyshop/fs/urls.py
from django.urls import path

from . import views

app_name = "fs"	
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
	path('users/register', views.RegisterView.as_view(), name='register'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('categories/<int:pk>/', views.SubcategoriesView.as_view(), name='subcategories'),
    path('products/', views.ProductsView.as_view(), name='products'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
   	path('products/new', views.CreateProductView.as_view(), name='new_product'),
   	path('products/<int:pk>/edit', views.UpdateProductView.as_view(), name='update_product'),
   	path('products/<int:pk>/delete', views.DeleteProductView.as_view(), name='delete_prodcut'),
   	path('letters/received', views.IndexRecieveLetterView.as_view(), name='received_letters'),
   	path('letters/sent', views.IndexSenderLetterView.as_view(), name='sent_letters'),
   	path('letters/<int:pk>', views.DetailLetterView.as_view(), name='letter_detail'),
   	path('letters/new', views.CreateLetterView.as_view(), name='new_letter'),
   	path('letters/<int:pk>/edit', views.UpdateLetterView.as_view(), name='update_letter'),
   	path('letters/<int:pk>/delete', views.DeleteLetterView.as_view(), name='delete_letter')
]

controls/control2/flankyshop/fs/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=64)
	body = models.CharField(max_length=128, null=True)

	def __str__(self):
		return self.name
		
class Subcategory(models.Model):
	name = models.CharField(max_length=64)
	body = models.CharField(max_length=128, null=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

class Product(models.Model):
	name = models.CharField(max_length=128)
	description = models.CharField(max_length=1024, null=True)
	subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
	price = models.FloatField(default=0)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

	def __str__(self):
		return self.name

class Letter(models.Model):
	sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
	receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver")
	body = models.TextField()
	date = models.DateTimeField(default=datetime.now())


	def __str__(self):
		return self.body

controls/control2/flankyshop/fs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import *

class RegistrationForm(UserCreationForm):
	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")
	

controls/control2/flankyshop/fs/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic
from django.views.generic.base import TemplateView

from .models import *
from .forms import *

# Create your views here.
class IndexView(TemplateView):
	template_name = "fs/index.html"


class RegisterView(generic.edit.FormView):
	form_class = RegistrationForm
	success_url = "/login"
	template_name = "registration/register.html"

	def form_valid(self, form):
		#TODO
		# сделать автологин
		
		form.save()
		return super().form_valid(form)

	def form_invalid(self, form):
		return super().form_invalid(form)


class CategoriesView(generic.ListView):
	template_name = "fs/categories.html"
	context_object_name = "categories"

	def get_queryset(self):
		return Category.objects.all()


class SubcategoriesView(generic.DetailView):
	model = Category	
	template_name = "fs/subcategories.html"
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)		
		context["subcategories"] = Subcategory.objects.filter(category=self.object.pk)
		return context


class ProductsView(generic.ListView):
	template_name = "fs/products.html"
	context_object_name = "products"

	def get_queryset(self):
		return Product.objects.all()


class ProductDetailView(generic.DetailView):
	model = Product


class CreateProductView(generic.edit.CreateView):
	model = Product
	template_name = "fs/new_product.html"
	fields = ['subcategory', 'name', 'description', 'price']

	# def get_context_data(self, **kwargs):
	# 	context = super(CreateProductView, self).get_context_data(**kwargs)
	# 	context['subcategory'] = Subcategory.objects.all()
	# 	return context

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("fs:index") #products

class UpdateProductView(generic.edit.UpdateView):
	model = Product
	template_name = "fs/update_product.html"
	fields = ['subcategory', 'name', 'description', 'price']

	def get_success_url(self):
		return reverse("fs:index")	#products

class DeleteProductView(generic.edit.DeleteView):
	model = Product
	template_name = "fs/delete_product.html"

	def get_success_url(self):
		return reverse("fs:index") #products



class IndexRecieveLetterView(generic.ListView):
	model = Letter
	context_object_name = "letters"
	template_name = "fs/received_letters.html"
	
	def get_queryset(self):
		return Letter.objects.filter(receiver=self.request.user)

class IndexSenderLetterView(generic.ListView):
	model = Letter
	context_object_name = "letters"
	template_name = "fs/sent_letters.html"
	
	def get_queryset(self):
		return Letter.objects.filter(sender=self.request.user)

class DetailLetterView(generic.DetailView):
	model = Letter



class CreateLetterView(generic.edit.CreateView):
	model = Letter
	template_name = "fs/new_letter.html"
	fields = ['receiver', 'body']
	
	def form_valid(self, form):
		form.instance.sender = self.request.user
		return super().form_valid(form)

	def get_success_url(self):
		return reverse("fs:index") #sent letters

class UpdateLetterView(generic.edit.UpdateView):
	model = Letter
	template_name = "fs/update_letter.html"
	fields = ['receiver', 'body']

	def get_success_url(self):
		return reverse("fs:index")	

class DeleteLetterView(generic.edit.DeleteView):
	model = Letter
	template_name = "fs/delete_letter.html"

	def get_success_url(self):
		return reverse("fs:index") 

controls/control2/flankyshop/fs/templates/fs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">	
	<title>Flanky Shop</title>

	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 	'materialize.min.css' %}">
	<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
	<script src="{% static 'materialize.min.js' %}"></script>
</head>
<body>
	<!-- Dropdown Structure -->
	<ul id="letters_dropdown" class="dropdown-content">
	  <li><a href="{% url 'fs:new_letter' %}">New</a></li>
	  <li class="divider"></li>
	  <li><a href="{% url 'fs:received_letters' %}">Received letters</a></li>
	  <li><a href="{% url 'fs:sent_letters' %}">Sent letters</a></li>
	</ul>

	<div class="navbar-wrapper">
		<nav>
		  <div class="nav-wrapper red lighten-1">
		    <a href="{% url 'fs:index' %}" class="brand-logo">		Flanky Shop
		    </a>


		   	<ul class="right hide-on-med-and-down">
		   		<li><a href="{% url 'fs:categories' %}">Catalog</a></li>
		   		<li><a href="{% url 'fs:products' %}">All products</a></li>
		    {% if user.is_authenticated %}
		    	<li><a href="#!" class="dropdown-trigger" data-target="letters_dropdown">Letters</a></li>
  				<li>{{ user.username }}</li>	
		      	<li><a href="/users/logout">Log out</a></li>
		    </ul>
		    {% else %}
		    <ul class="right hide-on-med-and-down">
		      	<li><a href="/users/login">Sign in</a></li>
		      	<li><a href="/users/register">Sign up</a></li>
		    {% endif %}
		    </ul>
		    
		  </div>
		</nav>
	</div>

	<div class="container">
	{% block content %}
	{% endblock %}
	</div>

	
	
	<script>
		$(document).ready(function() {
			$(".dropdown-trigger").dropdown();
		});
	</script>


</body>
</html>

controls/control2/flankyshop/fs/templates/fs/categories.html
{% extends "fs/base.html" %}

{% block content %}
<ul>
	{% for c in categories %}
		<li><a href="{% url 'fs:subcategories' c.id %}">{{ c }}</a></li>
	{% endfor %}		
</ul>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/delete_letter.html
{% extends "fs/base.html" %}


{% block content %}
	<form action="" method="post">
		{% csrf_token %}
	
		<h5>Delete product "<span class="teal-text lighten-1">{{ object }}</span>" ?</h5>
		<input type="submit" value="Delete" class="btn-small">
	</form>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/delete_product.html
{% extends "fs/base.html" %}


{% block content %}
	<form action="" method="post">
		{% csrf_token %}
	
		<h5>Delete letter "<span class="teal-text lighten-1">{{ object }}</span>" ?</h5>
		<input type="submit" value="Delete" class="btn-small">
	</form>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/index.html
{% extends "fs/base.html" %}

{% block content %}
	
	<h1 class="center-align">
		Hello
	</h1>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/letter_detail.html
{% extends "fs/base.html" %}

{% block content %}
	<h1>{{ product }}</h1>
	<p>From: {{ letter.sender }}</p>
	<p>To: {{ letter.receiver }}</p>	
	<p>Message: {{ letter.body }}</p>
	<p>Date: {{ letter.date }}</p>	
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/new_letter.html
{% extends "fs/base.html" %}


{% block content %}
	<h5>New letter</h5>

	<form action="" method="post">
		{% csrf_token %}

		{{ form.as_p }}
		<input type="submit" value="Send" class="btn-small">
	</form>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/new_product.html
{% extends "fs/base.html" %}


{% block content %}
	<h5>New product</h5>

	<form action="" method="post">
		{% csrf_token %}

		{{ form.as_p }}
		<input type="submit" value="Create" class="btn-small">
	</form>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/product_detail.html
{% extends "fs/base.html" %}

{% block content %}
	<h1>{{ product }}</h1>
	<p>{{ product.description }}</p>
	<p>{{ product.price }}</p>	
	<p><a href="#" class="">{{ product.subcategory }}</a></p>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/products.html
{% extends "fs/base.html" %}

{% block content %}
	<ul>
		{% for p in products %}
		<li><a href="{% url 'fs:product_detail' p.id %}">{{ p }}</a></li>
		{% endfor %}		
	</ul>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/received_letters.html
{% extends "fs/base.html" %}

{% block content %}
<ul>
{% for letter in letters %}
	<li><a href="{% url 'fs:letter_detail' letter.id %}">{{ letter }}</a></li>
{% endfor %}
</ul>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/sent_letters.html
{% extends "fs/base.html" %}

{% block content %}
<ul>
{% for letter in letters %}
	<li><a href="{% url 'fs:letter_detail' letter.id %}">{{ letter }}</a></li>
{% endfor %}
</ul>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/update_letter.html
{% extends "fs/base.html" %}

{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Save" class="btn-small">
	</form>
{% endblock %}

controls/control2/flankyshop/fs/templates/fs/update_product.html
{% extends "fs/base.html" %}

{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Save" class="btn-small">
	</form>
{% endblock %}