lessons/lesson14/helloworld/helloworld/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

lessons/lesson14/helloworld/polls/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
	#path('', views.index, name='index'),
	#path('<int:question_id>/', views.detail, name='detail'),
	#path('<int:question_id>/results', views.results, name='results'),
	
	path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
	path('<int:question_id>/vote', views.vote, name='vote'),
	path('login/', auth_views.LoginView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('register/', views.RegisterView.as_view(), name='register')
]

lessons/lesson14/helloworld/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
	body = models.CharField(max_length=200)
	pub_date = models.DateTimeField('publishing date', default=timezone.now())

	def __str__(self):
		return self.body

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	was_published_recently.admin_order_field = "pub_date"		# возможность сортировки = <по какому полю>
	was_published_recently.boolean = True		# символы вместо "True/False"
	was_published_recently.short_description = "Published recently?"	# отображение в заголовке

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	body = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.body

class UserChoice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	voting_date = models.DateTimeField(default=timezone.now())

	def __str__(self):
		return f"{self.question} => {self.user}"









# после каждого изменения (кроме методов) запускать: 
# 1) manage.py makemigrations polls
# 2) manage.py migrate

lessons/lesson14/helloworld/polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=200, help_text="Required")

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2") 

lessons/lesson14/helloworld/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .forms import RegistrationForm

from .models import Question, Choice, UserChoice


# Create your views here.
# def index(request):
# 	latest_question_list = Question.objects.order_by('pub_date')[:5]
# 	#output = ", ".join(q.body for q in latest_question_list)
# 	context = {'latest_question_list' : latest_question_list}
# 	return render(request, 'polls/index.html', context) 

class IndexView(generic.ListView):
	template_name = "polls/index.html"
	context_object_name = "latest_question_list"

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]	
		#__lte - <=
		# -pub_date - в порядке убывания
		

class DetailView(generic.DetailView):
	model = Question
	template_name = "polls/detail.html"

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())	
	

# def detail(request, question_id):	# request - обязателен для всех функций django
# 	# try:
# 	# 	question = Question.objects.get(pk=question_id)
# 	# except Question.DoesNotExist:
# 	# 	raise Http404("Question does not exists")
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, 'polls/detail.html', {'question': question})

# def results(request, question_id):
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, "polls/results.html", {'question': question})

class ResultsView(generic.DetailView):
	model = Question
	template_name = "polls/results.html"	

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())	
	
class RegisterView(generic.edit.FormView):
	form_class = RegistrationForm
	sucess_url = "/polls/login"
	template_name = "registration/register.html"

	def form_valid(self, form):
		form.save()
		return super(RegisterView, self).form_valid(form)

	def form_invalid(self, form):
		return super(RegisterView, self).form_invalid(form)


def vote(request, question_id):
	if request.user.is_authenticated:
		question = get_object_or_404(Question, pk=question_id)
		try:
			selected_choice = question.choice_set.get(pk=request.POST['choice'])
		except (KeyError, Choice.DoesNotExist):
			context = {"question": question, "error_message": "You didn't select choice"}
			return render(request, 'polls/detail.html', context)
		else:
			founded_user_choice = UserChoice.objects.filter(user=request.user, question=question)
			if not founded_user_choice:
				selected_choice.votes += 1
				selected_choice.save()

				user_choice = UserChoice(question=question, user=request.user)
				user_choice.save()
				return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))
			return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))
	else:
		return HttpResponseRedirect(reverse('polls:login'))

lessons/lesson14/helloworld/polls/templates/polls/detail.html
{% extends "polls/navbar.html" %}

{% block content %}
	<h1 class="question">{{ question }}</h1>

	{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
	{% endif %}

	<form action="{% url 'polls:vote' question.id %}" method="post">
		{% csrf_token %}
		{% for choice in question.choice_set.all%}
		<div class="form-check">
		  <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
		  <label class="form-check-label" for="hoice{{ forloop.counter }}">
		    {{ choice }}
		  </label>
		</div>
		{% endfor %}

		<input type="submit" value="Vote" class="btn btn-primary">
	</form>
{% endblock %}

lessons/lesson14/helloworld/polls/templates/polls/index.html
{% extends "polls/navbar.html" %}

{% block content %}
		<div class="list-group">
	{% if latest_question_list %}
		{% for question in latest_question_list%}
			<a href="/polls/{{ question.id }}" class="list-group-item list-group-item-action list-group-item-primary">{{ question.body }}</a>
		{% endfor %}
		</div>
	{% else %}
		<p>No polls are available</p>
	{% endif %} 
{% endblock %}

lessons/lesson14/helloworld/polls/templates/polls/navbar.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Polls</title>

	<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

	
</head>
<body>
	<nav class="navbar navbar-light bg-light">
  		<div class="container-fluid">
    		<a class="navbar-brand" href="{% url 'polls:index' %}">Polls</a>
  		</div>

  		{% if user.is_authenticated %}
  		<div class="dropdown">
			  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
			    {{ user.username }}
			  </button>
			  <ul class="dropdown-menu" aria-labelledby="dropdownMenuBu	tton">
			    <li><a class="dropdown-item" href="{% url 'polls:logout' %}">Logout</a></li>
			  </ul>
			</div>
			{% else %}
			<div class="dropdown">
			  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
			    Auth
			  </button>
			  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			    <li><a class="dropdown-item" href="{% url 'polls:login' %}">Login</a></li>
			    <li><a class="dropdown-item" href="{% url 'polls:register' %}">Register</a></li>
			  </ul>
			</div>
			{% endif %}

	</nav>	

	{% block content %}
	{% endblock %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

lessons/lesson14/helloworld/polls/templates/polls/results.html
{% extends "polls/navbar.html" %}

{% block content %}
	<h1 class="question">{{ question }}</h1>

	<ul class="list-group">
	{% for choice in question.choice_set.all %}
		<li class="	list-group-item">{{ choice }} -- {{ choice.votes }} vote{{choice.votes|pluralize}}</li>
	{% endfor %}
	</ul>

	<a href="{% url 'polls:detail' question.id%}" class="btn btn-primary">Vote again?</a>
{% endblock %}